import { ArrowUpRight, Check, Clock, CircleAlert, ShieldCheck, type LucideIcon } from 'lucide-react';
import type { ReactNode } from 'react';
import type { Role, Status } from '@/lib/types';
import { useDemo } from '@/lib/demo-context';
import { cn } from '@/lib/utils';
export function Money({amount,className,sign=false}:{amount:number;className?:string;sign?:boolean}){return <span className={cn('tabular-nums whitespace-nowrap',className)}>{sign&&amount>0?'+':''}{amount<0?'−':''}₹{Math.abs(amount).toLocaleString('en-IN',{maximumFractionDigits:0})}</span>}
export function formatDate(date:string){return new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${date}T00:00:00`))}
export function StatusChip({status}:{status:Status}){const warning=['Pending','Requested','Guarantor pending','Due'].includes(status), danger=status==='Overdue';const Icon=danger?CircleAlert:warning?Clock:Check;return <span className={cn('inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-medium whitespace-nowrap',danger?'bg-destructive/10 text-destructive':warning?'bg-gold-soft text-gold-foreground':'bg-primary/8 text-primary')}><Icon size={12}/>{status}</span>}
export function StatCard({title,amount,note,icon:Icon}:{title:string;amount:number;note:string;icon:LucideIcon}){return <article className="rounded-2xl border bg-card p-5 shadow-soft"><div className="flex items-center justify-between text-muted-foreground"><span className="text-xs font-medium">{title}</span><Icon size={18} strokeWidth={1.6}/></div><Money amount={amount} className="mt-3 block text-2xl font-semibold"/><div className="mt-2 flex items-center gap-1 text-[11px] text-muted-foreground"><ArrowUpRight size={13} className="text-primary"/>{note}</div></article>}
export function RoleGate({allowed,children,fallback=null}:{allowed:Role[];children:ReactNode;fallback?:ReactNode}){const {role}=useDemo();return allowed.includes(role)?children:fallback}
export function SectionHeading({title,subtitle,action}:{title:string;subtitle?:string;action?:ReactNode}){return <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</div>{action}</div>}
export function PrinciplesNote(){return <div className="flex items-center gap-3 text-xs text-muted-foreground"><ShieldCheck size={19} className="text-primary"/><span>Principal only. No interest. No fees. <span className="hidden sm:inline">Rooted in trust, sustained by community.</span></span></div>}
