import { useState, type ReactNode } from 'react';
import { Link, useRouterState } from '@tanstack/react-router';
import { ArrowLeftRight, ArrowUpRight, Bell, BookOpen, ChevronDown, CircleHelp, CirclePlus, HandCoins, HeartHandshake, LayoutDashboard, Leaf, LogOut, Moon, Settings, ShieldCheck, Sparkles, Sun, Users, Wallet, X, Check, ChevronsUpDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { useDemo } from '@/lib/demo-context';
import type { Role } from '@/lib/types';
const navigation=[{to:'/' as const,label:'Overview',icon:LayoutDashboard},{to:'/contributions' as const,label:'Contributions',icon:Wallet},{to:'/loans' as const,label:'Loans',icon:HandCoins},{to:'/ledger' as const,label:'Transparent ledger',icon:BookOpen},{to:'/members' as const,label:'Members',icon:Users}];
const roleDescriptions:Record<Role,string>={'Committee Admin':'Manage your community circle',Member:'Contribute and view your loans',Guarantor:'Review the requests you guarantee',Auditor:'Explore records in read-only mode'};
export function Brand({compact=false}:{compact?:boolean}){return <Link to="/" className="flex items-center gap-2.5"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary text-primary-foreground"><HeartHandshake size={23} strokeWidth={1.6}/></span><span className="font-display text-xl leading-5">Qard Hasan{!compact&&<span className="mt-1 block font-sans text-[10px] tracking-[.2em] text-muted-foreground">CIRCLES</span>}</span></Link>}
export function AppShell({children}:{children:ReactNode}){const {circle,user,role,dark,toggleTheme,switchRole}=useDemo();const pathname=useRouterState({select:s=>s.location.pathname});const [notifications,setNotifications]=useState(false);const [read,setRead]=useState(false);const [help,setHelp]=useState(false);const [switchOpen,setSwitchOpen]=useState(false);
const roles:Role[]=['Committee Admin','Member','Guarantor','Auditor'];
const pageTitles:Record<string,string>={'/':'Circle overview','/contributions':'Contributions','/loans':'Loans','/ledger':'Transparent ledger','/members':'Members','/committee':'Committee console','/rules':'Rules & principles','/settings':'Your profile'};
return <div className="min-h-screen">
<aside className="fixed inset-y-0 left-0 z-30 hidden w-[232px] flex-col border-r bg-sidebar lg:flex"><div className="px-6 pb-7 pt-8"><Brand/></div>
<div className="mx-4 rounded-xl border bg-card px-3 py-3"><div className="flex items-center justify-between"><span className="text-[9px] font-semibold tracking-[.13em] text-muted-foreground">YOUR CIRCLE</span><ChevronsUpDown size={13} className="text-muted-foreground"/></div><p className="mt-2 text-xs font-semibold">Mahallu Qard Hasan</p><p className="mt-1 truncate text-[10px] text-muted-foreground">Perinthalmanna Juma Masjid</p><div className="mt-2 flex items-center gap-1.5 text-[10px] text-primary"><span className="size-1.5 rounded-full bg-primary"/>Active circle</div></div>
<div className="mt-7 px-8 text-[9px] font-semibold tracking-[.14em] text-muted-foreground">COMMUNITY</div>
<nav aria-label="Main navigation" className="mt-3 space-y-1 px-4">{navigation.map(({to,label,icon:Icon})=><Button key={to} asChild variant="ghost" className="sidebar-link relative" data-active={pathname===to}><Link to={to}><Icon className="mr-1" size={18}/>{label}</Link></Button>)}{role==='Committee Admin'&&<Button asChild variant="ghost" className="sidebar-link relative" data-active={pathname==='/committee'}><Link to="/committee"><ShieldCheck className="mr-1"/>Committee console<span className="ml-auto flex size-5 items-center justify-center rounded-md bg-gold-soft text-[10px] text-gold-foreground">2</span></Link></Button>}</nav>
<div className="my-5 mx-7 border-t"/><nav aria-label="Circle preferences" className="space-y-1 px-4"><Button asChild variant="ghost" className="sidebar-link relative" data-active={pathname==='/rules'}><Link to="/rules"><Leaf className="mr-1"/>Rules & principles</Link></Button><Button asChild variant="ghost" className="sidebar-link relative" data-active={pathname==='/settings'}><Link to="/settings"><Settings className="mr-1"/>Settings</Link></Button></nav>
<div className="mt-auto p-4"><div className="rounded-xl border border-gold/25 bg-gold-soft/50 px-4 py-4"><div className="flex items-center gap-2 text-gold-foreground"><Leaf size={16}/><span className="font-display text-sm">Built on barakah.</span></div><p className="mt-2 text-[10px] leading-relaxed text-muted-foreground">A little from each of us.<br/>A world of difference for one of us.</p><Button asChild variant="link" className="mt-1 h-6 p-0 text-[10px]"><Link to="/rules">Our guiding principles <ArrowUpRight size={12}/></Link></Button></div><Button variant="ghost" onClick={()=>setHelp(true)} className="sidebar-link mt-3"><CircleHelp/>Help & support</Button><div className="mt-4 border-t pt-4"><div className="flex items-center gap-2.5"><span className="flex size-8 items-center justify-center rounded-full bg-secondary text-[11px] font-semibold text-primary">{user?.initials??'AK'}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{user?.name??'Abdul Kareem'}</p><p className="mt-0.5 text-[9px] text-muted-foreground">{role}</p></div><Button variant="ghost" size="icon" title="Switch demo profile" aria-label="Switch demo profile" className="size-7" onClick={()=>setSwitchOpen(true)}><LogOut size={14}/></Button></div></div></div></aside>
<div className="lg:ml-[232px]"><header className="flex h-[76px] items-center justify-between border-b bg-card px-5 sm:px-8"><div className="hidden items-center gap-2 text-xs text-muted-foreground sm:flex"><span>My circles</span><span className="mx-1 text-border">/</span><span className="text-foreground">{pageTitles[pathname]??'Circle overview'}</span></div><div className="sm:hidden"><Brand compact/></div><div className="flex items-center gap-2 sm:gap-4"><span className="hidden items-center gap-1.5 rounded-full border border-gold/25 bg-gold-soft/60 px-2.5 py-1 text-[10px] text-gold-foreground sm:flex"><span className="size-1.5 rounded-full bg-gold"/>Demo circle</span><Button variant="ghost" size="icon" aria-label={dark?'Switch to light theme':'Switch to dark theme'} title={dark?'Light theme':'Dark theme'} onClick={toggleTheme} className="size-8 text-muted-foreground">{dark?<Sun/>:<Moon/>}</Button><Popover open={notifications} onOpenChange={setNotifications}><PopoverTrigger asChild><Button variant="ghost" size="icon" title="Notifications" aria-label="Notifications" className="relative size-8 text-muted-foreground"><Bell/>{!read&&<span className="absolute right-2 top-1.5 size-1.5 rounded-full bg-gold"/>}</Button></PopoverTrigger><PopoverContent align="end" className="w-[310px] rounded-xl p-0"><div className="flex items-center justify-between border-b px-4 py-3"><h2 className="font-display">Notifications</h2><Button variant="link" className="h-auto p-0 text-[10px]" onClick={()=>setRead(true)}>Mark all read</Button></div>{[{title:'A little support goes a long way',body:'Two loan requests await committee review.'},{title:'Your circle is growing',body:'All 12 members are active in the circle.'},{title:'October installment reminder',body:'Your next installment is due on 15 October.'}].filter((_,i)=>role==='Committee Admin'?i<2:i>0).map(n=><div key={n.title} className="border-b px-4 py-4"><p className="text-xs font-medium">{n.title}</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">{n.body}</p></div>)}{read&&<p className="p-3 text-center text-[10px] text-primary">All caught up</p>}</PopoverContent></Popover><div className="hidden h-6 border-l sm:block"/><Button asChild variant="ghost" className="h-auto gap-2 rounded-full p-0"><Link to="/settings" aria-label="Your profile"><span className="flex size-8 items-center justify-center rounded-full bg-secondary text-[11px] font-semibold text-primary">{user?.initials??'AK'}</span><ChevronDown size={13} className="hidden text-muted-foreground sm:block"/></Link></Button></div></header>
<main className="mx-auto max-w-[1460px] px-5 pb-28 pt-7 sm:px-8 sm:pt-8 lg:pb-14">{children}<footer className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t pt-5 text-[10px] text-muted-foreground"><span className="flex items-center gap-1.5"><ShieldCheck size={13}/>A community of trust. A ledger of transparency.</span><span>Prototype · All money movement is simulated</span></footer></main></div>
<nav aria-label="Mobile navigation" className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-5 border-t bg-card pb-[env(safe-area-inset-bottom)] lg:hidden">{navigation.map(({to,label,icon:Icon})=><Button asChild variant="ghost" key={to} className={`h-16 flex-col gap-1 rounded-none px-1 text-[9px] ${pathname===to?'text-primary bg-secondary/60':'text-muted-foreground'}`}><Link to={to}><Icon size={20}/>{label==='Transparent ledger'?'Ledger':label}</Link></Button>)}</nav>
<Popover open={switchOpen} onOpenChange={setSwitchOpen}><PopoverTrigger asChild><Button className="demo-switcher fixed bottom-20 right-5 z-50 h-11 gap-2 rounded-full border border-gold/35 bg-card px-4 text-foreground shadow-lg hover:bg-secondary lg:bottom-6 lg:right-7"><ArrowLeftRight size={15} className="text-primary"/><span className="text-xs">Demo role</span><span className="hidden border-l pl-2 text-[11px] text-muted-foreground sm:inline">{role}</span><ChevronDown size={13}/></Button></PopoverTrigger><PopoverContent align="end" side="top" className="mb-2 w-[300px] rounded-2xl p-2"><div className="px-3 py-3"><span className="text-[10px] font-semibold tracking-[.1em] text-muted-foreground">EXPLORE THE CIRCLE</span><h2 className="mt-1 font-display text-lg">A different perspective</h2></div>{roles.map(r=><Button variant="ghost" key={r} onClick={()=>{switchRole(r);setSwitchOpen(false)}} className="h-auto w-full justify-start rounded-lg px-3 py-3"><span className="flex size-8 items-center justify-center rounded-lg bg-secondary text-primary">{r==='Committee Admin'?<ShieldCheck/>:r==='Member'?<Users/>:r==='Guarantor'?<HeartHandshake/>:<BookOpen/>}</span><span className="text-left"><span className="block text-xs">{r}</span><span className="mt-1 block text-[10px] font-normal text-muted-foreground">{roleDescriptions[r]}</span></span>{r===role&&<Check className="ml-auto text-primary"/>}</Button>)}<p className="px-3 pb-2 pt-3 text-[10px] text-muted-foreground">Demo profiles only. No real funds are moved.</p></PopoverContent></Popover>
{help&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/20 p-5"><div role="dialog" aria-modal="true" aria-labelledby="help-title" className="w-full max-w-sm rounded-2xl border bg-card p-6"><div className="flex items-center justify-between"><h2 id="help-title" className="font-display text-xl">Your community, here for you</h2><Button variant="ghost" size="icon" aria-label="Close help" onClick={()=>setHelp(false)}><X/></Button></div><p className="mt-4 text-sm leading-6 text-muted-foreground">For questions about contributions or repayment, please speak with the committee at Perinthalmanna Juma Masjid.</p><Button className="mt-5" onClick={()=>setHelp(false)}>Understood</Button></div></div>}
</div>}
